project:
  type: book
  output-dir: docs

book:
  title: "Models of Reality"
  subtitle: "From Data to Science"
  author: "<a href='https://www.hs-osnabrueck.de/prof-dr-jochen-kruppa/'>Prof. Dr. Jochen Kruppa-Scheetz</a>"
  date: "17. November 2025"
  favicon: cover2026_favi.png
  description: "*A book that takes you from data to science through models! I hope it provides some guidance in your life.*"
  url: https://jkruppa.github.io/biodatascience
  repo-url: https://github.com/jkruppa/jkruppa.github.io/biodatascience
  repo-branch: master
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  search: true
  page-footer:
    left: |
      Models of reality was written by <a href="https://www.hs-osnabrueck.de/prof-dr-jochen-kruppa/">Jochen Kruppa-Scheetz</a>. 
    right: |
      This open book was created using <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - part: chapter-00-preface.qmd
      chapters:
      - chapter-01-what-is-science.qmd
      - chapter-02-what-is-data.qmd
      - chapter-03-what-is-a-model.qmd
    - part: chapter-10-preface.qmd  
      chapters:
      - chapter-11-example-data.qmd   
    - part: template-preface.qmd
      chapters:
      - template-chapter.qmd

bibliography: references.bib
lang: en 

format:
  html: 
    theme:
      - united
      - bioscience.scss
    cover-image: cover2026b.png
    code-annotations: hover
    lightbox: true
    toc-expand: 2
    code-fold: show
    highlight-style: tango
    code-block-border-left: true
    code-summary: "R Code [show / hide]"
    code-tools: true
    mermaid:
      theme: neutral
      htmlLabels: true
  pdf:
    documentclass: scrreprt

