project:
  type: book
  output-dir: docs

book:
  title: "Models of Reality"
  subtitle: "From Data to Science"
  date: "20. November 2025"
  author:
  - name: Prof. Dr. Jochen Kruppa-Scheetz
    orcid: 0000-0001-8376-8864
    url: https://www.hs-osnabrueck.de/prof-dr-jochen-kruppa/
    email: j.kruppa@hs-osnabrueck.de
    corresponding: true
  favicon: cover2026_favi.png
  description: "*A book that takes you from data to science through models! I hope it provides some guidance in your life.*"
  url: https://jkruppa.github.io/biodatascience
  repo-url: https://github.com/jkruppa/biodatascience
  repo-branch: master
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  search: true
  page-footer:
    left: |
      Models of Reality was written by <a href="https://www.hs-osnabrueck.de/prof-dr-jochen-kruppa/">Jochen Kruppa-Scheetz</a>. 
    right: |
      This open book was created using <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - preface.qmd
    - part: chapter-00-preface.qmd
      chapters:
      - chapter-01-what-is-science.qmd
      - chapter-02-what-is-data.qmd
      - chapter-03-what-is-a-model.qmd
    - part: chapter-10-preface.qmd  
      chapters:
      - chapter-11-covariate-data.qmd
      - chapter-12-factorial-data.qmd   
      - chapter-13-combined-data.qmd
    - part: chapter-20-programing.qmd
      chapters:
      - chapter-21-programing-R.qmd
    - part: template-preface.qmd
      chapters:
      - template-chapter.qmd
  appendices:
    - appendix-a.qmd

bibliography: references.bib
lang: en 


format:
  html: 
    theme:
      - simplex
      - bioscience.scss
    cover-image: cover2026.png
    code-annotations: hover
    lightbox: true
    toc-expand: 2
    code-fold: show
    highlight-style: tango
    code-block-border-left: true
    code-summary: "R Code [show / hide]"
    code-tools: true
  pdf:
    documentclass: scrreprt

